"""Build, verify, or inertly restore a public/synthetic evidence package.

This command is intentionally limited to the portable package boundary.  It
does not publish material, adopt a source snapshot, make a review decision, or
handle applicant data.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections.abc import Sequence
from pathlib import Path

from .evidence_export import build_export, restore_export, verify_export
from .evidence_signature import (
    SignatureState,
    SignatureStatus,
    check_signature,
    default_allowed_signers,
    sign_archive,
    statement_matches_manifest,
)

ROOT = Path(__file__).resolve().parents[2]

#: Exit codes for the authenticity check, distinct so a partner's automation
#: can tell "nobody signed this" from "someone signed it and the signature is
#: wrong" from "someone signed it and we do not accept that someone". Collapsed
#: into one code they would be indistinguishable in a log, and the three call
#: for different responses.
EXIT_SIGNATURE_ABSENT = 3
EXIT_SIGNATURE_INVALID = 4
EXIT_SIGNATURE_UNKNOWN_SIGNER = 5

_SIGNATURE_EXIT_CODES = {
    SignatureState.ABSENT: EXIT_SIGNATURE_ABSENT,
    SignatureState.MALFORMED: EXIT_SIGNATURE_INVALID,
    SignatureState.INVALID: EXIT_SIGNATURE_INVALID,
    SignatureState.UNKNOWN_SIGNER: EXIT_SIGNATURE_UNKNOWN_SIGNER,
}


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="permit_pathways.evidence_export_cli",
        description=(
            "Build, verify, or inertly restore a pinned public/synthetic "
            "evidence package. The command does not publish, adopt, or "
            "approve its contents."
        ),
    )
    commands = parser.add_subparsers(dest="command", required=True)

    build = commands.add_parser(
        "build",
        help="create one deterministic ZIP_STORED package outside the repository",
    )
    build.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help="repository root containing the pinned export profile",
    )
    build.add_argument(
        "--output",
        type=Path,
        required=True,
        help="new archive path outside --root; an existing path is refused",
    )
    build.add_argument(
        "--freeze-id",
        required=True,
        help="stable identifier for this frozen package",
    )
    build.add_argument(
        "--frozen-on",
        required=True,
        help="freeze date in YYYY-MM-DD format",
    )
    build.add_argument(
        "--repository-commit-sha",
        default=None,
        help=(
            "optional full Git SHA; it is accepted only when it exactly "
            "matches the repository's verified HEAD"
        ),
    )
    build.add_argument(
        "--profile-version",
        type=int,
        choices=(1, 2),
        default=None,
        help=(
            "versioned export profile to build; when omitted, the newest profile "
            "present is selected (v2 in the current repository); v1 is frozen "
            "and may not match current generated bytes"
        ),
    )
    build.add_argument(
        "--sign-key",
        type=Path,
        default=None,
        help=(
            "OpenSSH private key; writes a detached signature over the "
            "archive's canonical digest to <archive>.sig.json. The archive "
            "bytes are identical with and without this flag"
        ),
    )
    build.add_argument(
        "--signer-identity",
        default=None,
        help=(
            "principal to record in the signature, matched against a line in "
            "the allowed-signers file at verification time; defaults to the "
            "signing key's own comment"
        ),
    )

    verify = commands.add_parser(
        "verify",
        help="verify archive structure, raw hashes, profile pins, and public state",
    )
    verify.add_argument("--archive", type=Path, required=True)
    _add_signers_argument(verify)

    restore = commands.add_parser(
        "restore",
        help="verify then restore into a new clean destination without adoption",
    )
    restore.add_argument("--archive", type=Path, required=True)
    restore.add_argument(
        "--destination",
        type=Path,
        required=True,
        help="new destination directory; an existing path is refused",
    )
    _add_signers_argument(restore)
    return parser


def _add_signers_argument(command: argparse.ArgumentParser) -> None:
    """Asking for authenticity is opt-in, and asking makes absence a failure.

    Without this flag the signature state is reported and nothing is gated,
    because a signature nobody asked to check attests to nothing. With it, an
    unsigned archive is a failed authenticity check rather than a silent pass.
    """

    command.add_argument(
        "--allowed-signers",
        type=Path,
        default=None,
        help=(
            "OpenSSH allowed_signers file; supplying it requires a signature "
            "by a listed principal. Defaults to .github/allowed_signers when "
            "--use-repository-signers is given"
        ),
    )
    command.add_argument(
        "--use-repository-signers",
        action="store_true",
        help="use .github/allowed_signers from --root, or the repository root",
    )
    command.add_argument(
        "--root",
        type=Path,
        default=ROOT,
        help="checkout to resolve --use-repository-signers against",
    )


def _emit(payload: dict[str, object]) -> None:
    """Print a stable machine-readable evidence manifest."""

    sys.stdout.write(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    )


def main(argv: Sequence[str] | None = None) -> int:
    """Run the explicitly selected bounded evidence-package operation."""

    args = _parser().parse_args(argv)
    if args.command == "build":
        return _build(args)
    return _read(args)


def _build(args: argparse.Namespace) -> int:
    try:
        manifest = build_export(
            args.root,
            args.output,
            freeze_id=args.freeze_id,
            frozen_on=args.frozen_on,
            repository_commit_sha=args.repository_commit_sha,
            profile_version=args.profile_version,
        )
        status = None
        if args.sign_key is not None:
            sign_archive(
                args.output,
                manifest,
                key_path=args.sign_key,
                signer_identity=args.signer_identity,
            )
            status = check_signature(args.output, manifest)
    except (OSError, ValueError) as error:
        print(f"evidence export: invalid input or output: {error}", file=sys.stderr)
        return 2
    _emit(_with_signature(manifest, status))
    return 0


def _read(args: argparse.Namespace) -> int:
    """Check the signature first, then the archive's structure.

    The order is the point. A partner asking "did this reach me unchanged, from
    you" is asking about the whole archive's bytes, and one altered byte moves
    the digest the signature covers. Running structural verification first
    would answer with a changed member -- true, but not the question, and it
    would not say whether the *original* was ever yours. So the digest and the
    signature are settled before the archive is opened.
    """

    try:
        signers = _resolve_allowed_signers(args)
        status = check_signature(args.archive, allowed_signers=signers)
    except (OSError, ValueError) as error:
        print(f"evidence export: signature error: {error}", file=sys.stderr)
        return 2

    demanded = signers is not None
    if demanded and not status.is_verified:
        _emit({"signature": status.to_json()})
        print(f"evidence export: {status.detail}", file=sys.stderr)
        return _SIGNATURE_EXIT_CODES.get(status.state, EXIT_SIGNATURE_INVALID)

    try:
        if args.command == "verify":
            manifest = verify_export(args.archive)
        else:
            manifest = restore_export(args.archive, args.destination)
    except (OSError, ValueError) as error:
        print(f"evidence export: invalid input or output: {error}", file=sys.stderr)
        return 2

    # A signature over the right bytes still has to describe the right package.
    if status.signed_statement is not None and not statement_matches_manifest(
        status, manifest
    ):
        status = SignatureStatus(
            state=SignatureState.INVALID,
            signer=status.signer,
            detail=(
                "the signed statement does not describe this package's "
                "manifest; the signature covers a different freeze or profile"
            ),
            archive_sha256=status.archive_sha256,
            signed_statement=status.signed_statement,
        )
        _emit(_with_signature(manifest, status))
        print(f"evidence export: {status.detail}", file=sys.stderr)
        return EXIT_SIGNATURE_INVALID

    _emit(_with_signature(manifest, status))
    return 0


def _with_signature(
    manifest: dict[str, object], status: SignatureStatus | None
) -> dict[str, object]:
    if status is None:
        return manifest
    return {**manifest, "signature": status.to_json()}


def _resolve_allowed_signers(args: argparse.Namespace) -> Path | None:
    """The signers file this run must satisfy, or ``None`` to only report.

    Supplying one is how a caller asks for authenticity; without it the
    signature state is printed and nothing is gated, because a signature no one
    asked to check attests to nothing.
    """

    explicit = getattr(args, "allowed_signers", None)
    if explicit is not None:
        return Path(explicit)
    if not getattr(args, "use_repository_signers", False):
        return None
    resolved = default_allowed_signers(getattr(args, "root", ROOT))
    if resolved is None:
        raise ValueError(
            "--use-repository-signers was given but .github/allowed_signers "
            "is not a regular file in this checkout"
        )
    return resolved


if __name__ == "__main__":
    raise SystemExit(main())
